version: "3.7"

services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --ISCAgent false
    restart: always
    ports: 
      - 41773:1972
      - 42773:52773
      - 443:443
    volumes:
      - ./:/irisrun/repo

